# 中国移动 Cookie/登录参数获取（Quantumult X 重写资源）
# 仓库：https://github.com/zmnxx/vps/tree/main/qx/cookie
# 抓取：打开移动 App → 手机验证码登录（人脸登录通常无效）

hostname = client.app.coc.10086.cn

# 中国移动 Cookie/登录参数
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/[LD]N\/(uam(onekey|randcode)login|realPersonAuthentication)\/autoLogin url script-request-body https://raw.githubusercontent.com/zmnxx/vps/main/qx/cookie/china_mobile_cookie.js
