# 中国联通 Cookie
# 圈X：风车 → 重写 → 引用 本文件
# 抓取：打开联通App → 首页点 流量/语音
# 通知正文即完整 Cookie

hostname = m.client.10010.com

^https?:\/\/m\.client\.10010\.com\/.+\/smartwisdomCommon url script-request-header https://raw.githubusercontent.com/zmnxx/vps/main/qx/cookie/china_unicom_cookie.js
