# 中国移动 Cookie/登录参数获取 - Quantumult X
# 仓库：https://github.com/zmnxx/vps/tree/main/圈X/cookie
# 抓取：打开移动 App → 手机验证码登录（人脸登录通常无效）

[rewrite_local]
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/[LD]N\/(uam(onekey|randcode)login|realPersonAuthentication)\/autoLogin url script-request-body https://raw.githubusercontent.com/zmnxx/vps/main/%E5%9C%88X/cookie/china_mobile_cookie.js

[mitm]
hostname = client.app.coc.10086.cn
